ARG ENV_TARGET

FROM node:16-alpine as build
WORKDIR /app
COPY . ./
RUN cat .env
RUN yarn install
RUN yarn build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 9400
CMD ["nginx", "-g", "daemon off;"]
